### ISSUE TITLE
How to train and eval the model fairly?

### ISSUE THREAD

**Issue by kxhit** [PRBonn/overlap_localization#3]
Hi @Chen-Xieyuanli . Sorry to bother you. It's me again [: )]

I found the provided model in the zip file. It seems the model is trained on KITTI seq 07 with a train/val split. I know it's a toy example for users to understand how it works. I have two questions:
1. What should I do if I wish to evaluate overlap model's performance on KITTI fairly? I think one workable way is to train the model on other sequences and test it on seq 07. 
2. How does the overlap model trained on single scans perform on a scan to local map test? I guess there exists some gap between "scan to scan" and "scan to local map".

I would be very appreciate if you can give me some advice. Thanks a lot!

**Comment by Chen-Xieyuanli** [comment]
You are right that we use KITTI seq 07 only as a toy example and keep it consistent with our OverlapNet framework.

1. However, the KITTI dataset is not suitable for testing global localization methods and we therefore collected our own car dataset which is described in our iros 2020 paper.

2. Yes, usually for the global localization problem the global map is assumed to be given, which is different from the place recognition or loop closing problem.

I'm very glad you are interested in this topic and we may discuss more via WeChat or even cooperate later if you want ;-) .

**Comment by kxhit** [comment]
Thanks!
